[build-system]
#cmake
#requires = ["setuptools_scm","setuptools>=42", "PySide2>=5.15.2.1", "pybind11>=2.10.0", "cmake>=3.12", "wheel", "ninja"]
requires = ["setuptools_scm","setuptools>=42", "PySide2>=5.15.2.1", "pybind11>=2.10.0"]
build-backend= "setuptools.build_meta"
